# Generated by Django 5.2.17 on 2026-09-29 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Legt die initialen Frage-, Test- und Mitarbeiterdatenmodelle an."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Fragetext')),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('short', 'Kurzantwort'), ('long', 'Lange Antwort / Freitext')], max_length=12, verbose_name='Fragetyp')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Antwortoptionen')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Punkte')),
                ('answer_key', models.TextField(blank=True, verbose_name='Musterlösung')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Verankert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
                'permissions': [('can_manage_questions', 'Fragenpool einsehen und verwalten'), ('can_generate_tests', 'Tests und Einmalpasswörter generieren'), ('can_view_submissions', 'Testergebnisse und Abgaben einsehen'), ('can_grade_submissions', 'Freitextantworten bewerten'), ('can_manage_users', 'Mitarbeiter und Rechte verwalten')],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Test-UUID')),
                ('otp_hash', models.CharField(max_length=256, verbose_name='OTP-Hash')),
                ('status', models.CharField(choices=[('issued', 'Ausgestellt'), ('completed', 'Abgeschlossen')], default='issued', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('text', models.TextField(verbose_name='Fragetext')),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('short', 'Kurzantwort'), ('long', 'Lange Antwort / Freitext')], max_length=12, verbose_name='Fragetyp')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Optionen und interne Lösungsschlüssel')),
                ('points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punkte')),
                ('answer_key', models.TextField(blank=True, verbose_name='Musterlösung')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.testsession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=dict, verbose_name='Antwort')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Erreichte Punkte')),
                ('needs_manual_grading', models.BooleanField(default=False, verbose_name='Manuelle Korrektur erforderlich')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Bewertet am')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.testquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.testsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'position'), name='unique_test_question_position'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('test', 'test_question'), name='unique_submission_per_test_question'),
        ),
    ]
