# Generated by Django 5.2.17 on 2026-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """Speichert den Namen des Prüflings direkt am Testlauf."""

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='examinee_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name des Prüflings'),
        ),
    ]
