# Generated by Django 5.2.17 on 2026-10-01 17:33

from django.db import migrations


class Migration(migrations.Migration):
    """Aktualisiert Modelloptionen und globale Poolverwaltungsrechte."""

    dependencies = [
        ("core", "0006_alter_question_question_pool_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-is_pinned", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="questionpool",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_manage_users", "Mitarbeiter, Gruppen und Rechte verwalten"),
                    ("can_delete_tests", "Abgegebene Tests löschen"),
                    ("can_view_audit_logs", "Systemprotokoll einsehen"),
                ],
            },
        ),
    ]
