# Generated by Django 5.2.17 on 2026-10-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testsession_timing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpool',
            options={'ordering': ['name'], 'permissions': [('can_manage_users', 'Mitarbeiter, Gruppen und Rechte verwalten'), ('can_manage_tool_settings', 'Seiteneinstellungen verwalten'), ('can_delete_tests', 'Abgegebene Tests löschen'), ('can_view_audit_logs', 'Systemprotokoll einsehen'), ('can_clear_audit_logs', 'Systemprotokoll leeren'), ('can_grant_user_permissions', 'Nutzerrechte vergeben'), ('can_revoke_user_permissions', 'Nutzerrechte entziehen'), ('can_grant_administrator', 'Administratorstatus vergeben'), ('can_revoke_administrator', 'Administratorstatus entziehen')]},
        ),
    ]
