# Generated by Django 5.2.17 on 2026-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_questionpool_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="otp_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Einmalpasswort bestätigt am"
            ),
        ),
    ]
