# Generated by Django 5.2.18 on 2026-10-08 20:40

import django.core.validators
from django.db import migrations, models


def copy_maximum_to_fixed_count(apps, schema_editor):
    """Übernimmt die bisherige Höchstzahl als feste Fragenzahl."""
    QuestionPool = apps.get_model("core", "QuestionPool")
    for pool in QuestionPool.objects.all():
        pool.test_question_count = max(pool.maximum_test_questions, 1)
        pool.save(update_fields=["test_question_count"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pool_test_question_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpool',
            name='test_question_count',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Fragenzahl je Test'),
        ),
        migrations.RunPython(copy_maximum_to_fixed_count, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='questionpool',
            name='maximum_test_questions',
        ),
        migrations.RemoveField(
            model_name='questionpool',
            name='minimum_test_questions',
        ),
        migrations.AddField(
            model_name='questionpool',
            name='maximum_time_limit_minutes',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximales Zeitlimit in Minuten'),
        ),
        migrations.AddField(
            model_name='questionpool',
            name='minimum_time_limit_minutes',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimales Zeitlimit in Minuten'),
        ),
        migrations.AddField(
            model_name='questionpool',
            name='pass_percentage',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bestehgrenze in Prozent'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='pass_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bestehgrenze in Prozent (bei Erstellung)'),
        ),
    ]
