# Generated by Django 5.2.18 on 2026-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_questionpool_start_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpool',
            name='start_info_text',
            field=models.TextField(blank=True, help_text='Optionaler längerer Text, der vor Testbeginn angezeigt wird. Links: [Text](https://…) oder einfach die URL einfügen. Der Prüfling bestätigt ihn mit einer Checkbox „Gelesen und verstanden“.', verbose_name='Infotext vor Testbeginn'),
        ),
    ]
